CREATE TABLE `crm_contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(128) NOT NULL,
	`fullNameAr` varchar(128),
	`company` varchar(128),
	`companyAr` varchar(128),
	`email` varchar(320),
	`phone` varchar(32),
	`type` enum('lead','prospect','client','partner') NOT NULL DEFAULT 'lead',
	`stage` enum('new','contacted','qualified','proposal','negotiation','won','lost') NOT NULL DEFAULT 'new',
	`dealValue` bigint,
	`probability` int DEFAULT 0,
	`source` varchar(64),
	`assignedTo` varchar(128),
	`notes` text,
	`lastContactDate` varchar(32),
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crm_contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `erp_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`recordNumber` varchar(32),
	`type` enum('sale','invoice','purchase','inventory','expense','other') NOT NULL DEFAULT 'sale',
	`title` varchar(256) NOT NULL,
	`titleAr` varchar(256),
	`party` varchar(128),
	`partyAr` varchar(128),
	`amount` bigint,
	`currency` varchar(8) DEFAULT 'SAR',
	`status` enum('draft','pending','approved','paid','cancelled') NOT NULL DEFAULT 'draft',
	`dueDate` varchar(32),
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `erp_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `legal_cases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseNumber` varchar(32),
	`title` varchar(256) NOT NULL,
	`titleAr` varchar(256),
	`type` enum('contract','dispute','compliance','ip','employment','other') NOT NULL DEFAULT 'contract',
	`party` varchar(128),
	`partyAr` varchar(128),
	`value` bigint,
	`status` enum('draft','active','expiring_soon','expired','closed','disputed') NOT NULL DEFAULT 'draft',
	`startDate` varchar(32),
	`expiryDate` varchar(32),
	`description` text,
	`descriptionAr` text,
	`assignedTo` varchar(128),
	`notes` text,
	`closedAt` timestamp,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `legal_cases_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `qms_incidents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`incidentCode` varchar(32),
	`title` varchar(256) NOT NULL,
	`titleAr` varchar(256),
	`area` varchar(128),
	`areaAr` varchar(128),
	`description` text,
	`severity` enum('critical','major','minor','observation') NOT NULL DEFAULT 'minor',
	`status` enum('open','in_progress','resolved','closed') NOT NULL DEFAULT 'open',
	`assignedTo` varchar(128),
	`rootCause` text,
	`correctiveAction` text,
	`dueDate` varchar(32),
	`closedAt` timestamp,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `qms_incidents_id` PRIMARY KEY(`id`)
);
