/**
 * Reports Page — /portal/reports
 * Displays scheduled weekly AI KPI reports with search, pagination, and Markdown rendering.
 * Admin-only access.
 */
import { useState, useMemo } from "react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  FileText, Search, ChevronLeft, ChevronRight,
  Calendar, Loader2, AlertCircle, RefreshCw, BarChart3,
} from "lucide-react";
import { Streamdown } from "streamdown";

const PAGE_SIZE = 10;

function formatDate(dateStr: string | Date | null | undefined): string {
  if (!dateStr) return "—";
  return new Date(dateStr).toLocaleString(undefined, {
    year: "numeric", month: "short", day: "numeric",
    hour: "2-digit", minute: "2-digit",
  });
}

function ReportTypeBadge({ type }: { type: string }) {
  const map: Record<string, { label: string; className: string }> = {
    weekly_kpi:    { label: "Weekly KPI",    className: "bg-amber-500/20 text-amber-600 border-amber-500/30" },
    odoo_summary:  { label: "Odoo Summary",  className: "bg-blue-500/20 text-blue-600 border-blue-500/30" },
    monthly:       { label: "Monthly",       className: "bg-purple-500/20 text-purple-600 border-purple-500/30" },
  };
  const config = map[type] ?? { label: type, className: "bg-muted text-muted-foreground" };
  return (
    <Badge variant="outline" className={`text-xs ${config.className}`}>
      {config.label}
    </Badge>
  );
}

export default function Reports() {
  const { user } = useAuth();
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [page, setPage] = useState(1);
  const [selectedReport, setSelectedReport] = useState<{
    id: number; title: string; content: string; reportType: string;
    periodStart?: string | null; periodEnd?: string | null;
    createdAt: string | Date;
  } | null>(null);

  // Debounce search input
  const handleSearch = (value: string) => {
    setSearch(value);
    clearTimeout((window as unknown as { _searchTimer?: ReturnType<typeof setTimeout> })._searchTimer);
    (window as unknown as { _searchTimer?: ReturnType<typeof setTimeout> })._searchTimer = setTimeout(() => {
      setDebouncedSearch(value);
      setPage(1);
    }, 400);
  };

  const { data, isLoading, error, refetch, isFetching } = trpc.modules.getReports.useQuery({
    search: debouncedSearch || undefined,
    page,
    pageSize: PAGE_SIZE,
  });

  const totalPages = useMemo(() => Math.max(1, Math.ceil((data?.total ?? 0) / PAGE_SIZE)), [data?.total]);

  if (user?.role !== "admin") {
    return (
      <div className="p-4 sm:p-6 flex items-center justify-center min-h-[40vh]">
        <Card className="max-w-sm w-full">
          <CardContent className="pt-6 flex flex-col items-center gap-3 text-center">
            <AlertCircle className="w-10 h-10 text-muted-foreground" />
            <p className="text-muted-foreground">Only administrators can view AI reports.</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="p-4 sm:p-6 max-w-5xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-xl sm:text-2xl font-bold text-foreground flex items-center gap-2">
            <BarChart3 className="w-6 h-6 text-amber-500 shrink-0" />
            AI Reports
          </h1>
          <p className="text-muted-foreground mt-1 text-sm">
            Scheduled weekly KPI and Odoo summary reports generated by NEO.
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => refetch()}
          disabled={isFetching}
          className="self-start sm:self-auto gap-2"
        >
          <RefreshCw className={`w-4 h-4 ${isFetching ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      {/* Search */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground pointer-events-none" />
        <Input
          placeholder="Search reports by title or content..."
          value={search}
          onChange={(e) => handleSearch(e.target.value)}
          className="pl-9"
        />
      </div>

      {/* Stats bar */}
      {data && (
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <FileText className="w-4 h-4" />
          <span>
            {data.total === 0
              ? "No reports found"
              : `${data.total} report${data.total === 1 ? "" : "s"} total`}
            {debouncedSearch && ` matching "${debouncedSearch}"`}
          </span>
        </div>
      )}

      {/* Loading state */}
      {isLoading && (
        <div className="flex items-center justify-center py-16 gap-3 text-muted-foreground">
          <Loader2 className="w-5 h-5 animate-spin" />
          <span>Loading reports...</span>
        </div>
      )}

      {/* Error state */}
      {error && (
        <Card className="border-destructive/50">
          <CardContent className="pt-6 flex items-center gap-3 text-destructive">
            <AlertCircle className="w-5 h-5 shrink-0" />
            <p className="text-sm">Failed to load reports: {error.message}</p>
          </CardContent>
        </Card>
      )}

      {/* Empty state */}
      {!isLoading && !error && data?.reports.length === 0 && (
        <Card>
          <CardContent className="pt-10 pb-10 flex flex-col items-center gap-4 text-center">
            <div className="w-16 h-16 rounded-full bg-muted flex items-center justify-center">
              <FileText className="w-8 h-8 text-muted-foreground" />
            </div>
            <div>
              <p className="font-medium text-foreground">No reports yet</p>
              <p className="text-sm text-muted-foreground mt-1">
                {debouncedSearch
                  ? `No reports match "${debouncedSearch}". Try a different search term.`
                  : "Weekly AI reports will appear here once the scheduled task runs. Reports are generated every Sunday at 8:00 AM."}
              </p>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Report cards */}
      {!isLoading && !error && data && data.reports.length > 0 && (
        <div className="space-y-3">
          {data.reports.map((report) => (
            <Card
              key={report.id}
              className="cursor-pointer hover:border-amber-500/50 hover:shadow-md transition-all duration-200 group"
              onClick={() => setSelectedReport(report as typeof selectedReport)}
            >
              <CardHeader className="pb-2">
                <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2">
                  <div className="flex items-start gap-3 min-w-0">
                    <div className="w-9 h-9 rounded-lg bg-amber-500/10 flex items-center justify-center shrink-0 mt-0.5 group-hover:bg-amber-500/20 transition-colors">
                      <FileText className="w-4 h-4 text-amber-500" />
                    </div>
                    <div className="min-w-0">
                      <CardTitle className="text-sm sm:text-base font-semibold leading-tight truncate">
                        {report.title}
                      </CardTitle>
                      <div className="flex flex-wrap items-center gap-2 mt-1.5">
                        <ReportTypeBadge type={report.reportType} />
                        {report.periodStart && report.periodEnd && (
                          <span className="text-xs text-muted-foreground flex items-center gap-1">
                            <Calendar className="w-3 h-3" />
                            {report.periodStart} — {report.periodEnd}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="text-xs text-muted-foreground shrink-0 sm:text-right">
                    {formatDate(report.createdAt)}
                  </div>
                </div>
              </CardHeader>
              <CardContent className="pt-0">
                <CardDescription className="text-xs sm:text-sm line-clamp-2">
                  {report.content.slice(0, 200).replace(/[#*`]/g, "")}
                  {report.content.length > 200 ? "…" : ""}
                </CardDescription>
                <p className="text-xs text-amber-500 mt-2 group-hover:underline">
                  Click to read full report →
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Pagination */}
      {!isLoading && !error && totalPages > 1 && (
        <div className="flex items-center justify-between pt-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setPage((p) => Math.max(1, p - 1))}
            disabled={page <= 1 || isFetching}
            className="gap-1.5"
          >
            <ChevronLeft className="w-4 h-4" />
            <span className="hidden sm:inline">Previous</span>
          </Button>
          <span className="text-sm text-muted-foreground">
            Page {page} of {totalPages}
          </span>
          <Button
            variant="outline"
            size="sm"
            onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
            disabled={page >= totalPages || isFetching}
            className="gap-1.5"
          >
            <span className="hidden sm:inline">Next</span>
            <ChevronRight className="w-4 h-4" />
          </Button>
        </div>
      )}

      {/* Report detail dialog */}
      <Dialog open={!!selectedReport} onOpenChange={(open) => { if (!open) setSelectedReport(null); }}>
        <DialogContent className="max-w-3xl w-[95vw] max-h-[90vh] flex flex-col">
          <DialogHeader className="shrink-0">
            <DialogTitle className="flex items-start gap-3 pr-6">
              <FileText className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
              <span className="leading-tight">{selectedReport?.title}</span>
            </DialogTitle>
            {selectedReport && (
              <div className="flex flex-wrap items-center gap-2 mt-2">
                <ReportTypeBadge type={selectedReport.reportType} />
                {selectedReport.periodStart && selectedReport.periodEnd && (
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <Calendar className="w-3 h-3" />
                    {selectedReport.periodStart} — {selectedReport.periodEnd}
                  </span>
                )}
                <span className="text-xs text-muted-foreground">
                  Generated: {formatDate(selectedReport.createdAt)}
                </span>
              </div>
            )}
          </DialogHeader>
          <div className="flex-1 overflow-y-auto mt-4 pr-1">
            {selectedReport && (
              <div className="prose prose-sm dark:prose-invert max-w-none">
                <Streamdown>{selectedReport.content}</Streamdown>
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
